/**
 * Auto-generated Tileset Configuration
 * Generated by Visual Tile Connector
 * 
 * 9 tiles defined with 2 unique socket patterns
 */

import type { TileDefinition } from '../types';

export const NATURE_TILE_SIZE = 16;

export const natureTiles: TileDefinition[] = [
    {
        id: 'tile_5_2',
        position: { x: 5, y: 2 },
        weight: 1,
        sockets: { up: 's0', down: 's0', left: 's1', right: 's1' }
    },
    {
        id: 'tile_6_2',
        position: { x: 6, y: 2 },
        weight: 1,
        sockets: { up: 's0', down: 's0', left: 's1', right: 's1' }
    },
    {
        id: 'tile_5_5',
        position: { x: 5, y: 5 },
        weight: 1,
        sockets: { up: 's0', down: 's0', left: 's1', right: 's1' }
    },
    {
        id: 'tile_6_5',
        position: { x: 6, y: 5 },
        weight: 1,
        sockets: { up: 's0', down: 's0', left: 's1', right: 's1' }
    },
    {
        id: 'tile_4_4',
        position: { x: 4, y: 4 },
        weight: 1,
        sockets: { up: 's0', down: 's0', left: 's1', right: 's1' }
    },
    {
        id: 'tile_5_4',
        position: { x: 5, y: 4 },
        weight: 1,
        sockets: { up: 's0', down: 's0', left: 's1', right: 's1' }
    },
    {
        id: 'tile_6_4',
        position: { x: 6, y: 4 },
        weight: 1,
        sockets: { up: 's0', down: 's0', left: 's1', right: 's1' }
    },
    {
        id: 'tile_7_4',
        position: { x: 7, y: 4 },
        weight: 1,
        sockets: { up: 's0', down: 's0', left: 's1', right: 's1' }
    },
    {
        id: 'tile_7_5',
        position: { x: 7, y: 5 },
        weight: 1,
        sockets: { up: 's0', down: 's0', left: 's1', right: 's1' }
    }
];

export const simpleNatureTiles = natureTiles;

export default natureTiles;
